apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    manager: kube-controller-manager
    {{- include "hello-ami-part2.labels" . | nindent 4 }}
  name: {{ include "hello-ami-part2.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hello-ami-part2.selectorLabels" . | nindent 4 }}
